import os from "os"

console.info(os.platform())
console.info(os.arch())
console.info(os.cpus())
console.info(os.freemem())
console.info(os.totalmem())
console.info(os.homedir())
console.info(os.hostname())
console.info(os.networkInterfaces())
console.info(os.release())
console.info(os.tmpdir())
console.info(os.type())
console.info(os.uptime())
console.info(os.userInfo())
console.info(os.version())
